apiVersion: v1
kind: Pod
metadata:
  annotations:
    capabilities: Basic Install
    categories: OpenShift Optional, Integration & Delivery
    certified: "false"
    containerImage: quay.io/openshift/origin-federation-controller:latest
    createdAt: "2019-01-01T00:00:00Z"
    description: Cluster-scoped Federation
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.130.0.45"
          ],
          "default": true,
          "dns": {}
      }]
    olm.operatorGroup: cluster-scoped-federation
    olm.operatorNamespace: federation-test
    olm.targetNamespaces: ""
    openshift.io/scc: anyuid
  generateName: federation-controller-manager-
  labels:
    app: federation-controller-manager
  name: federation-controller-manager-8495f6fb7c-f9j2k
  namespace: federation-test
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
spec:
  containers:
  - args:
    - --federation-namespace=$(FEDERATION_NAMESPACE)
    - --registry-namespace=$(CLUSTER_REGISTRY_NAMESPACE)
    - -v=5
    - --logtostderr
    command:
    - /root/controller-manager
    env:
    - name: FEDERATION_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CLUSTER_REGISTRY_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/openshift/origin-federation-controller:latest
    imagePullPolicy: Always
    name: controller-manager
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      capabilities:
        drop:
        - MKNOD
      procMount: Default
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: federation-controller-manager-token-d4cwv
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: federation-controller-manager-dockercfg-4sdnb
  nodeName: ip-10-0-135-91.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: s0:c22,c4
  serviceAccount: federation-controller-manager
  serviceAccountName: federation-controller-manager
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: federation-controller-manager-token-d4cwv
    secret:
      defaultMode: 420
      secretName: federation-controller-manager-token-d4cwv

