apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedSecret
metadata:
  name: s3-bucket-owner
  namespace: federation-test
spec:
  template:
    data:
      AWS_ACCESS_KEY_ID: QUtJQUlPN0RERjJRUUFXSEtSVUE=
      AWS_SECRET_ACCESS_KEY: Y3pWNDJaazdOQUcvVkxyV1JYNVRDS3ZpVm5jL3VLOTNXRENxaGNlSg==
    type: Opaque
  placement:
    clusterNames:
    - cluster2
    - cluster1

