[root@ip-10-0-30-109 ~]# kubectl get pvc -n rook-ceph
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
mysql-pv-claim   Bound    pvc-d8028ed9-1593-4bff-8633-7f1cc770cd6c   10Gi       RWO            csi-rook-ceph-block   26h

---------
--PVs
---------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-mirror
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: rook-ceph
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-ceph-csi
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: "2"
      pool: testpool
      storage.kubernetes.io/csiProvisionerIdentity: 1570032265647-8081-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-a9bf434b-e534-11e9-bfb7-ea481d76b4b8
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-rook-ceph-block
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-wordpress-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: wp-pv-claim
    namespace: rook-ceph
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-ceph-csi
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: "2"
      pool: testpool
      storage.kubernetes.io/csiProvisionerIdentity: 1570032265647-8081-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-f558e5d3-e534-11e9-bfb7-ea481d76b4b8
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-rook-ceph-block
  volumeMode: Filesystem

------
PVCs
------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"mysql-pv-claim","namespace":"rook-ceph"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"csi-rook-ceph-block"}}
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  labels:
    app: wordpress
  name: mysql-pv-claim
  namespace: rook-ceph
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rook-ceph-block
  volumeMode: Filesystem
  volumeName: mysql-pv-mirror
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"wp-pv-claim","namespace":"rook-ceph"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"csi-rook-ceph-block"}}
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  labels:
    app: wordpress
  name: wp-pv-claim
  namespace: rook-ceph
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rook-ceph-block
  volumeMode: Filesystem
  volumeName: my-wordpress-pv








