apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-owner
  namespace: s3-provisioner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQUlPN0RERjJRUUFXSEtSVUE=
  AWS_SECRET_ACCESS_KEY: Y3pWNDJaazdOQUcvVkxyV1JYNVRDS3ZpVm5jL3VLOTNXRENxaGNlSg==

